"""Crear modelos

Revision ID: 60cd8ddfb818
Revises: 213b1202accb
Create Date: 2023-12-19 09:18:07.086864

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60cd8ddfb818'
down_revision: Union[str, None] = '213b1202accb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuario', sa.Column('estado_civil', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuario', 'estado_civil')
    # ### end Alembic commands ###
