"""Crear modelos

Revision ID: e84e1afe2071
Revises: 60cd8ddfb818
Create Date: 2023-12-19 09:19:01.474543

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e84e1afe2071'
down_revision: Union[str, None] = '60cd8ddfb818'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuario', 'estado_civil')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuario', sa.Column('estado_civil', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
